name: Deploy Node.js App

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests (optional, add if needed)
    - name: Run tests
      run: npm test

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t your-dockerhub-username/static-nodejs-app .

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push your-dockerhub-username/static-nodejs-app

    # Deploy to your server
    - name: Deploy application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        docker pull your-dockerhub-username/static-nodejs-app
        docker stop static-nodejs-app || true
        docker rm static-nodejs-app || true
        docker run -d --name static-nodejs-app -p 3000:3000 your-dockerhub-username/static-nodejs-app
        EOF
zzz
