name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests defined."

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/nodejs-backend-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push your-dockerhub-username/nodejs-backend-app

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker pull your-dockerhub-username/nodejs-backend-app
          docker stop nodejs-backend-app || true
          docker rm nodejs-backend-app || true
          docker run -d --name nodejs-backend-app -p 3000:3000 your-dockerhub-username/nodejs-backend-app
          EOF
