name: Deploy Node.js App

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: raghavi123
          password: Raghavi123$

      # Build Docker image
      - name: Build Docker image
        run: docker build -t your-dockerhub-username/static-nodejs-app .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push your-dockerhub-username/static-nodejs-app

      # SSH into the server and deploy the app
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker pull your-dockerhub-username/static-nodejs-app
          docker stop static-nodejs-app || true
          docker rm static-nodejs-app || true
          docker run -d --name static-nodejs-app -p 3000:3000 your-dockerhub-username/static-nodejs-app
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


